AcerCMS/Models/News.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AcerCMS.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class News
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string ShortDesctription { get; set; }
        public string Content { get; set; }
        public System.DateTime UpdateDate { get; set; }
        public bool IsDeleted { get; set; }
        public int ViewCount { get; set; }
        public Nullable<int> PictureId { get; set; }
    
        public virtual Picture Picture { get; set; }
    }
}

AcerCMS/Models/NewsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace AcerCMS.Models
{
    public class NewsViewModel
    {
        public News News { get; set; }
        //public List<Comment> Comments { get; set; }
        //public Comment Comment { get; set; }
    }
}

AcerCMS/Controllers/CommentController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Runtime.CompilerServices;
using System.Web;
using System.Web.Mvc;
using AcerCMS.Filters;
using AcerCMS.Models;
using AcerCMS.ModelService;

namespace AcerCMS.Controllers
{
    public class CommentController : Controller
    {
        //// GET: Comment
        //public ActionResult Index()
        //{
        //    return View();
        //}

        //// GET: Comment/Details/5
        //public ActionResult Details(int id)
        //{
        //    return View();
        //}

        // GET: Comment/Create
        //[ChildActionOnly]
        [MergeModelState]
        [ShowMessage]
        public ActionResult Create(int entityId, EntityType entity)
        {            
            var model = CommentModelService.CreateCommentViewModel(entityId, entity);
            return PartialView("_CommentFormPartial", model);
        }

        // POST: Comment/Create
        [HttpPost]
        public ActionResult Create(Comment comment)
        {
            if (!ModelState.IsValid)
            {
                ModelState.AddModelError("", "Lütfen bilgileri kontrol ederek tekrar deneyiniz!");
                TempData["ModelState"] = ModelState;
                return RedirectToAction("Create", new {entityId = comment.EntityId, entity = comment.Entity});
            }

            try
            {
                CommentModelService.Save(comment);
                TempData["Message"] = "Tebrikler! Kayıt Başarıyla Eklenmiştir!";
            }
            catch (Exception ex)
            {
                //Log Error;
                Elmah.ErrorSignal.FromCurrentContext().Raise(ex);
                TempData["Message"] = "HATA! Kayıt Eklenemedi!";                
            }

            return RedirectToAction("GetComments", new { entityId = comment.EntityId, entity = comment.Entity });
        }

        public ActionResult GetComments(int entityId, EntityType entity)
        {
            var model = CommentModelService.GetComments(entityId, entity);
            return PartialView("_CommentsPartial", model);
        }

        // GET: Comment/Edit/5s        
        public ActionResult Edit(int id)
        {
            return View();
        }

        // POST: Comment/Edit/5
        [HttpPost]
        public ActionResult Edit(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add update logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }

        // GET: Comment/Delete/5
        public ActionResult Delete(int id)
        {
            return View();
        }

        // POST: Comment/Delete/5
        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

AcerCMS/Controllers/NewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using AcerCMS.Models;
using AcerCMS.ModelService;

namespace AcerCMS.Controllers
{
    public class NewsController : Controller
    {
        // GET: News
        public ActionResult Index()
        {
            var model = NewsModelService.GetIndexViewModel();
            return View(model);
        }

        public ActionResult ReadNews(int id)
        {
            var model = NewsModelService.ReadNews(id);
            
            if(model== null)
                return HttpNotFound("Haber Bulunamadı!");

            return View(model);           
        }

    }
}

AcerCMS/Views/News/Index.cshtml
@model IEnumerable<AcerCMS.Models.News>

@{
    ViewBag.Title = "Haberler Ve Duyurular";
}

<h2>Son Haberler</h2>
@if (Model.Any())
{
    <ul class="list-group">

        @foreach (var news in Model)
        {
            <li class="list-group-item">
                <h3>
                    @news.Title <small>@news.UpdateDate.ToShortDateString()</small>
                    <span class="label label-info">@news.ViewCount</span>
                </h3>
                <p class="lead">@news.ShortDesctription</p>
                <p class="text-right">
                    @Html.ActionLink("Devami için Tıklayınız...", "ReadNews", "News", new {id= news.Id}, null)
                </p>    
            </li>
        }
    </ul>
}
else
{
    <div class="alert alert-warning">
        Henüz Haber Eklenmemiş!
    </div>
}

AcerCMS/Views/News/ReadNews.cshtml
@model NewsViewModel

@{
    ViewBag.Title = Model.News.Title;
}

<h2>@Model.News.Title </h2>
<p class="lead">@Model.News.ShortDesctription</p>

<hr />

<div>
    @Model.News.Content
</div>

<hr />
@Html.Action("GetComments", "Comment", new {entityId=Model.News.Id, entity= EntityType.News})

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    @Scripts.Render("~/bundles/jqueryajax")

    <script>
        function HideAlert() {
            $('div#addCommentAlert').hide();
        }
    </script>
}